
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.net.HttpURLConnection;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author pabloantoniolopezmartin
 */
public class MainFrame extends javax.swing.JFrame {
 
    
    private Double[] rate=new Double[]{0.0,0.0};
    private int currentRate=0;
    
    public MainFrame() throws IOException {
        initComponents();
        setValue();
        initButtonGroup();
    }
    public void setValue() throws MalformedURLException, IOException{
        URL url = new URL("https://api.exchangeratesapi.io/latest?symbols=USD");
        HttpURLConnection conn = (HttpURLConnection) url.openConnection();
        conn.setRequestMethod("GET");
	conn.setRequestProperty("Accept", "application/json");
        BufferedReader br = new BufferedReader(new InputStreamReader(
			(conn.getInputStream())));
        String output;
     
        while ((output = br.readLine()) != null) {
                    rate[0]=Double.parseDouble(output.substring(16, 22));
                    rate[1]= 1/rate[0];
		}
        if(dolarToEuroButton.isSelected()){
            currentRate=1;
        } else {
            currentRate=0;
        }
        actualChangeRateLabel.setText(String.format("%.3f", rate[currentRate]));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        cantidadLabel = new javax.swing.JLabel();
        ammountTextField = new javax.swing.JTextField();
        valueLabel = new javax.swing.JLabel();
        actualChangeRateLabel = new javax.swing.JLabel();
        refreshButton = new javax.swing.JButton();
        resultLabel = new javax.swing.JLabel();
        resultAmmountLabel = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();
        warningLabel = new javax.swing.JLabel();
        calculateButton = new javax.swing.JButton();
        roundingButton = new javax.swing.JButton();
        euroToDollarButton = new javax.swing.JRadioButton();
        dolarToEuroButton = new javax.swing.JRadioButton();
        authorsLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cantidadLabel.setText("Cantidad (€):");

        ammountTextField.setText("1");

        valueLabel.setText("Valor del cambio actual:");

        refreshButton.setText("Refresh");
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });

        resultLabel.setText("Resultado ($):");

        titleLabel.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        titleLabel.setText("CONVERSOR DE DIVISAS");

        warningLabel.setForeground(new java.awt.Color(255, 0, 51));

        calculateButton.setText("Calcular");
        calculateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateButtonActionPerformed(evt);
            }
        });

        roundingButton.setText("Redondear cambio");
        roundingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roundingButtonActionPerformed(evt);
            }
        });

        euroToDollarButton.setText("EUR (€) To DOLLAR ($)");
        euroToDollarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                euroToDollarButtonActionPerformed(evt);
            }
        });

        dolarToEuroButton.setText("DOLLAR ($) to EUR (€)");
        dolarToEuroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dolarToEuroButtonActionPerformed(evt);
            }
        });

        authorsLabel.setText("Azael Santana Enríquez y Pablo López Martín");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cantidadLabel)
                            .addComponent(valueLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(resultAmmountLabel)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ammountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(actualChangeRateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(refreshButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(calculateButton))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(euroToDollarButton)
                                            .addComponent(roundingButton)
                                            .addComponent(dolarToEuroButton))))
                                .addGap(0, 22, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(resultLabel)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(titleLabel))
                    .addComponent(authorsLabel)
                    .addComponent(warningLabel))
                .addGap(143, 143, 143))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(titleLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cantidadLabel)
                    .addComponent(ammountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valueLabel)
                    .addComponent(actualChangeRateLabel)
                    .addComponent(refreshButton)
                    .addComponent(roundingButton))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(resultLabel)
                            .addComponent(resultAmmountLabel)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(euroToDollarButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dolarToEuroButton)
                            .addComponent(calculateButton))))
                .addGap(61, 61, 61)
                .addComponent(warningLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(authorsLabel)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        try {
            setValue();
            resultAmmountLabel.setText("");
        } catch (IOException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_refreshButtonActionPerformed

    private void calculateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateButtonActionPerformed
        try{
           resultAmmountLabel.setText(Double.toString(new BigDecimal(Double.parseDouble(ammountTextField.getText())*rate[currentRate]).setScale(2, RoundingMode.HALF_EVEN).doubleValue()));
           warningLabel.setText("");
       }catch(NumberFormatException e){
           warningLabel.setText("Introduzca solo números, use '.' para los decimales");
           resultAmmountLabel.setText("");
       }
    }//GEN-LAST:event_calculateButtonActionPerformed

    private void roundingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roundingButtonActionPerformed
        try {
            setValue();
        } catch (IOException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        rate[currentRate]= new BigDecimal(rate[currentRate]).setScale(2, RoundingMode.HALF_EVEN).doubleValue();
        actualChangeRateLabel.setText(String.format("%.2f",rate[currentRate]));
        resultAmmountLabel.setText("");
    }//GEN-LAST:event_roundingButtonActionPerformed

    private void dolarToEuroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dolarToEuroButtonActionPerformed
        try {
            setValue();
        } catch (IOException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        cantidadLabel.setText("Cantidad ($):");
        resultLabel.setText("Resultado (€):");
        resultAmmountLabel.setText("");
    }//GEN-LAST:event_dolarToEuroButtonActionPerformed

    private void euroToDollarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_euroToDollarButtonActionPerformed
        try {
            setValue();
        } catch (IOException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        cantidadLabel.setText("Cantidad (€):");
        resultLabel.setText("Resultado ($):");
        resultAmmountLabel.setText("");
    }//GEN-LAST:event_euroToDollarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MainFrame().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel actualChangeRateLabel;
    private javax.swing.JTextField ammountTextField;
    private javax.swing.JLabel authorsLabel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton calculateButton;
    private javax.swing.JLabel cantidadLabel;
    private javax.swing.JRadioButton dolarToEuroButton;
    private javax.swing.JRadioButton euroToDollarButton;
    private javax.swing.JButton refreshButton;
    private javax.swing.JLabel resultAmmountLabel;
    private javax.swing.JLabel resultLabel;
    private javax.swing.JButton roundingButton;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel valueLabel;
    private javax.swing.JLabel warningLabel;
    // End of variables declaration//GEN-END:variables

    private void initButtonGroup() {
        buttonGroup1.add(euroToDollarButton);
        buttonGroup1.add(dolarToEuroButton);
        euroToDollarButton.setSelected(true);
        
    }
}
